<?php

namespace CB\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * @param $username
     * @return array
     */
    public function findByUsernameChunk($username)
    {
        $username = '%'.$username.'%';
        return $this->createQueryBuilder('u')
            ->select('u.username, u.roles')
            ->andWhere('u.username LIKE :username')
            ->setParameter('username', $username)
            ->orderBy('u.username', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }

    public function isUser($username)
    {
        $result = $this->createQueryBuilder('u')
            ->andWhere('u.username = :username')
            ->setParameter('username', $username)
            ->getQuery()
            ->getOneOrNullResult()
        ;

        return $result?true:false;
    }

    public function findUsersWithBoothTimes()
    {
        return $this->createQueryBuilder('u')
            ->select('f.username as child, f.eldestGrade as grade, u.name as parent, u.phone, b.name as booth, t.time as time, t.duration as duration')
            ->innerJoin('u.times', 't')
            ->innerJoin('t.booth', 'b')
            ->innerJoin('u.family', 'f')
            ->getQuery()
            ->getResult();
    }
}
