<?php

namespace CB\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findByUsernameChunk($username)
    {
        $username = '%'.$username.'%';
        return $this->createQueryBuilder('u')
            ->select('u.username')
            ->andWhere('u.username LIKE :username')
            ->setParameter('username', $username)
            ->orderBy('u.username', 'ASC')
            ->getQuery()
            ->getResult()
        ;
    }
}
