<?php

namespace CB\FairBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends EntityRepository
{
    public function passesRule($hours, $baked, $auction)
    {

        $rules = $this->createQueryBuilder('r')
            ->getQuery()
            ->getResult()
        ;

        /** @var \CB\FairBundle\Entity\Rule $rule */
        foreach ($rules as $rule) {
            if ($rule->hasEnoughHours($hours) && $rule->hasEnoughBakedItems($baked) && $rule->hasEnoughAuctionItems($auction)) {
                return true;
            }
        }

        return false;
    }
}
