<?php

namespace CB\FairBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserTimeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTimeRepository extends EntityRepository
{
}
